/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "ApiKey": {                                      "en": "API key",                                         "de": "API-Schlüssel",                                   "ru": "ключ API",                                        "pt": "Chave API",                                       "nl": "API sleutel",                                     "fr": "Clé API",                                         "it": "Chiave API",                                      "es": "Clave API",                                       "pl": "Klucz API",                                       "zh-cn": "API 密钥"},
    "IsDonated": {                                   "en": "donation status",                                 "de": "wird gespendet",                                  "ru": "статус пожертвования",                            "pt": "status de doação",                                "nl": "donatiestatus",                                   "fr": "état du don",                                     "it": "stato di donazione",                              "es": "estado de donación",                              "pl": "status darowizny",                                "zh-cn": "捐赠状况"},
    "Main settings": {                               "en": "Main settings",                                   "de": "Haupteinstellungen",                              "ru": "Основные параметры",                              "pt": "Configurações principais",                        "nl": "Belangrijkste instellingen",                      "fr": "Réglages principaux",                             "it": "Impostazioni principali",                         "es": "Ajustes principales",                             "pl": "Ustawienia główne",                               "zh-cn": "主要设置"},
    "SystemId": {                                    "en": "System ID",                                       "de": "System-ID",                                       "ru": "Идентификатор системы",                           "pt": "ID do sistema",                                   "nl": "Systeem-ID",                                      "fr": "ID système",                                      "it": "ID di sistema",                                   "es": "identificación del sistema",                      "pl": "Identyfikator systemu",                           "zh-cn": "系统编号"},
    "name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "Имя",                                             "pt": "Nome",                                            "nl": "Naam",                                            "fr": "Nom",                                             "it": "Nome",                                            "es": "Nombre",                                          "pl": "Nazwać",                                          "zh-cn": "姓名"},
    "pvoutputorg adapter settings": {                "en": "Adapter settings for pvoutputorg",                "de": "Adaptereinstellungen für pvoutputorg",            "ru": "Настройки адаптера для pvoutputorg",              "pt": "Configurações do adaptador para pvoutputorg",     "nl": "Adapterinstellingen voor pvoutputorg",            "fr": "Paramètres de l'adaptateur pour pvoutputorg",     "it": "Impostazioni dell'adattatore per pvoutputorg",    "es": "Configuración del adaptador para pvoutputorg",    "pl": "Ustawienia adaptera dla pvoutputorg",             "zh-cn": "pvoutputorg 的适配器设置"},
    "readInterval": {                                "en": "interval to read data [min]",                     "de": "Intervall zum Lesen von Daten [min]",             "ru": "интервал чтения данных [мин]",                    "pt": "intervalo para ler os dados [min]",               "nl": "interval om gegevens te lezen [min]",             "fr": "intervalle de lecture des données [min]",         "it": "intervallo di lettura dei dati [min]",            "es": "intervalo para leer datos [min]",                 "pl": "interwał odczytu danych [min]",                   "zh-cn": "读取数据的间隔 [分钟]"},
    "systems": {                                     "en": "System",                                          "de": "System",                                          "ru": "Система",                                         "pt": "Sistema",                                         "nl": "Systeem",                                         "fr": "Système",                                         "it": "Sistema",                                         "es": "Sistema",                                         "pl": "System",                                          "zh-cn": "系统"},
};